### ISSUE TITLE
Cannot Install Plug-in

### ISSUE THREAD

**Issue by softwud** [Mr0grog/editorconfig-textmate#40] opened 2020-02-05 23:45 UTC
I just installed TextMate version 2.0.6 for the first time and when I try to double click on the editorconfig-textmate.tmplugin file as per you instructions it TextMate show a dialog box titled "Cannot Install Plug-in" and the text "The editorconfig-textmate plug-in is not compatible with this version of TextMate."

If there is a solution to this please let me know at softwud@softwud.com

**Comment by Mr0grog** [comment] 2020-02-06 19:08
Are you using the latest version ([v0.4.0](https://github.com/Mr0grog/editorconfig-textmate/releases/tag/v0.4.0))? It seems to still be working fine for me with TM v2.0.6.

What version of MacOS are you running?
Do you have any other plug-ins installed/what is in your `~/Library/Application Support/TextMate/PlugIns` directory?

**Comment by Mr0grog** [comment] 2021-05-28 05:42
Closing this since there hasn’t been any activity and I cannot reproduce the issue.

**Closed by Mr0grog** 2021-05-28 05:42 UTC
